<?php
// Adds option group for SqltasksAction

return [
  [
    'name' => 'SqltasksAction',
    'entity' => 'OptionGroup',
    'cleanup' => 'never',
    'params' => [
      'name' => 'sqltasks_action',
      'title' => 'Sql Tasks Action',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:RunSQL',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_RunSQL',
      'value' => 'CRM_Sqltasks_Action_RunSQL',
      'label' => 'Run SQL',
      'weight' => 10,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:SegmentationAssign',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_SegmentationAssign',
      'value' => 'CRM_Sqltasks_Action_SegmentationAssign',
      'label' => 'Assign to Campaign (Segmentation)',
      'weight' => 20,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:CreateActivity',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_CreateActivity',
      'value' => 'CRM_Sqltasks_Action_CreateActivity',
      'label' => 'Create Activity',
      'weight' => 30,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:APICall',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_APICall',
      'value' => 'CRM_Sqltasks_Action_APICall',
      'label' => 'API Call',
      'weight' => 40,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:CSVExport',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_CSVExport',
      'value' => 'CRM_Sqltasks_Action_CSVExport',
      'label' => 'CSV Export',
      'weight' => 50,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:SyncTag',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_SyncTag',
      'value' => 'CRM_Sqltasks_Action_SyncTag',
      'label' => 'Synchronise Tag',
      'weight' => 60,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:SyncGroup',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_SyncGroup',
      'value' => 'CRM_Sqltasks_Action_SyncGroup',
      'label' => 'Synchronise Group',
      'weight' => 70,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:SegmentationExport',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_SegmentationExport',
      'value' => 'CRM_Sqltasks_Action_SegmentationExport',
      'label' => 'Segmentation Export',
      'weight' => 80,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:CallTask',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_CallTask',
      'value' => 'CRM_Sqltasks_Action_CallTask',
      'label' => 'Run SQL Task(s)',
      'weight' => 90,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:RunPHP',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_RunPHP',
      'value' => 'CRM_Sqltasks_Action_RunPHP',
      'label' => 'Run PHP',
      'weight' => 100,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:PostSQL',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_PostSQL',
      'value' => 'CRM_Sqltasks_Action_PostSQL',
      'label' => 'Run Cleanup SQL Script',
      'weight' => 110,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:SuccessHandler',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_SuccessHandler',
      'value' => 'CRM_Sqltasks_Action_SuccessHandler',
      'label' => 'Success Handler',
      'weight' => 120,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
  [
    'name' => 'SqltasksAction:ErrorHandler',
    'entity' => 'OptionValue',
    'cleanup' => 'never',
    'params' => [
      'option_group_id' => 'sqltasks_action',
      'name' => 'CRM_Sqltasks_Action_ErrorHandler',
      'value' => 'CRM_Sqltasks_Action_ErrorHandler',
      'label' => 'Error Handler',
      'weight' => 130,
      'icon' => 'fa-tasks',
      'is_active' => 1,
    ],
  ],
];
