<?php

return [
  'sqltasks_global_tokens' => [
    'name'        => 'sqltasks_global_tokens',
    'type'        => 'Array',
    'default'     => [],
    'html_type'   => 'text',
    'title'       => ts('SQL Tasks global tokens'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Array of global tokens for SQL Tasks which may be used using the {config.token_name} syntax.'),
  ],
  'sqltasks_default_template' => [
    'name'        => 'sqltasks_default_template',
    'type'        => 'String',
    'default'     => null,
    'html_type'   => 'text',
    'title'       => ts('SQL Tasks default template'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Default configuration (ID) for new SQL Tasks.'),
  ],
  'sqltask_export_append_scripts' => [
    'name'        => 'sqltask_export_append_scripts',
    'type'        => 'Boolean',
    'default'     => TRUE,
    'html_type'   => 'checkbox',
    'title'       => ts('SQL Tasks Export: Append Scripts?'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Should task export files include a read-only version of the included SQL and PHP scripts?'),
  ],
  'sqltasks_is_dispatcher_disabled' => [
    'name'            => 'sqltasks_is_dispatcher_disabled',
    'type'            => 'Boolean',
    'html_type'       => 'text',
    'default'         => '0',
    'title'           => ts('Is SQL Task Dispatcher disabled?'),
    'is_domain'       => 1,
    'is_contact'      => 0,
    'description'     => ts('Disables automatic task execution of scheduled tasks via the dispatcher'),
  ],
  'sqltasks_max_fails_number' => [
    'name'        => 'sqltasks_max_fails_number',
    'type'        => 'String',
    'default'     => '0',
    'html_type'   => 'text',
    'title'       => ts('Maximum number of SQL Task Fails'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Maximum number of fails before dispatcher is disabled. Defaults to 0 (no limit)'),
  ],
  'sqltasks_sftp_max_retries' => [
    'name'        => 'sqltasks_sftp_max_retries',
    'type'        => 'Integer',
    'default'     => 5,
    'html_type'   => 'text',
    'title'       => ts('SQL Tasks sftp max retries'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Maximum retries for sftp upload from SQL Tasks.'),
  ],
  'sqltasks_sftp_retry_initial_wait' => [
    'name'        => 'sqltasks_sftp_retry_initial_wait',
    'type'        => 'Integer',
    'default'     => 1,
    'html_type'   => 'text',
    'title'       => ts('SQL Tasks sftp initial wait'),
    'is_domain'   => 1,
    'is_contact'  => 0,
    'description' => ts('Initial wait for retry sftp upload from SQL Tasks.'),
  ],
];
